file_format: "1"
id: dactyl_corne
name: Dactyl Corne
type: shield
url: https://github.com/ccai89/Dactyl Corne
requires: [seeeduino_xiao_ble]
features:
  - keys
  - studio
siblings:
  - dactyl_corne_left
  - dactyl_corne_right
