manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      revision: main
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
